/**
 * Chinese labels for portfolio credit departments and roles.
 *
 * Sourced from TranslatePress + live vantage.pictures/zh/portfolio curated
 * industry terms (manual overrides where TRP was literal or missing).
 */

/** EN label (after pluralizeCreditRole) → ZH display label. */
export const CREDIT_LABEL_ZH: Record<string, string> = {
  // Departments
  Production: '制作',
  Camera: '摄影组',
  'G&E': '灯光与器材组',
  Art: '美术组',
  Casting: '选角',
  Stills: '平面摄影组',
  Post: '后期制作',

  // Production
  Brand: '品牌方',
  Agency: '机构',
  Agencies: '机构',
  'Production Company': '制作公司',
  'Production Companies': '制作公司',
  'Production Service': '制片服务',
  'Production Services': '制作服务',
  EP: '执行制片人',
  EPs: '执行制片人',
  Director: '导演',
  Directors: '导演',
  'Creative Director': '创意总监',
  'Creative Directors': '创意总监',
  Producer: '制片人',
  Producers: '制片人',
  'Line Producer': '统筹制片',
  'Line Producers': '统筹制片',
  'Production Manager': '制片经理',
  'Production Managers': '制片经理',
  'Production Coordinator': '制片协调',
  'Production Coordinators': '制片协调',
  '1st AD': '第一副导演',
  '1st ADs': '第一副导演',
  '2nd AD': '第二副导演',
  '2nd ADs': '第二副导演',
  PA: '制片助理',
  PAs: '制片助理',
  'Product Technician': '产品技术支持',
  'Product Technicians': '产品技术支持',
  'Account Manager': '客户经理',
  'Account Managers': '客户经理',
  Transport: '交通组',
  Chaperone: '客户助理',
  Chaperones: '客户助理',
  BTS: '花絮团队',

  // Camera
  DOP: '摄影指导',
  DOPs: '摄影指导',
  'Camera Op': '摄影师',
  'Camera Ops': '摄影师',
  'Steadicam Op': '斯坦尼康操作员',
  'Steadicam Ops': '斯坦尼康操作员',
  '1st AC': '第一助理摄影',
  '1st ACs': '第一助理摄影',
  '2nd AC': '第二助理摄影',
  '2nd ACs': '第二助理摄影',
  'Focus Puller': '跟焦员',
  'Focus Pullers': '跟焦员',
  DIT: '数字影像技术员',
  DITs: '数字影像技术员',
  QTake: 'QTake',
  'Drone Op': '无人机操作员',
  'Drone Ops': '无人机操作员',
  'Motion Control': '动控团队',

  // G&E
  'Rental House': '器材租赁公司',
  'Rental Houses': '器材租赁公司',
  Gaffer: '灯光指导',
  Gaffers: '灯光指导',
  'Key Grip': '场务指导',
  'Key Grips': '场务指导',
  Grip: '场务',
  Grips: '场务',
  Electrician: '电工',
  Electricians: '电工',

  // Art
  'Production Designer': '美术指导',
  'Production Designers': '美术指导',
  'Art Director': '美术指导',
  'Art Directors': '美术指导',
  'Art Assistant': '美术助理',
  'Art Assistants': '美术助理',
  'Props Master': '道具师',
  'Props Masters': '道具师',
  Wardrobe: '造型组',
  'Hair & Makeup': '化妆组',
  'Location Manager': '场地经理',
  'Location Managers': '场地经理',
  Storyboards: '分镜师',

  // Casting
  'Casting Director': '选角导演',
  'Casting Directors': '选角导演',
  'Casting Manager': '选角统筹',
  'Casting Managers': '选角统筹',
  Talent: '演员',
  'Stunt Coordinator': '动作指导',
  'Stunt Coordinators': '动作指导',
  Choreographer: '编舞',
  Choreographers: '编舞',
  'Animal Wrangler': '动物管理',
  'Animal Wranglers': '动物管理',

  // Stills
  Photographer: '摄影师',
  Photographers: '摄影师',
  'Photography Producer': '摄影制片',
  'Photography Producers': '摄影制片',
  'KV Art Director': '关键视觉艺术指导',
  'KV Art Directors': '关键视觉艺术指导',
  'Photography Assistant': '摄影助理',
  'Photography Assistants': '摄影助理',
  'Photo Talent': '平面演员',

  // Post
  'Post Supervisor': '后期制片',
  'Post Supervisors': '后期制片',
  'On-Set Editor': '现场剪辑师',
  'On-Set Editors': '现场剪辑师',
  Editor: '剪辑师',
  Editors: '剪辑师',
  'Assistant Editors': '剪辑助理',
  Colorist: '调色师',
  Colorists: '调色师',
  'Sound Design & Mix': '声音设计与混音',
  'Sound Engineer': '录音师',
  'Sound Engineers': '录音师',
  Composer: '作曲',
  Composers: '作曲',
  'Voice Over': '配音',
  VFX: '视效团队',
  Online: 'Online',
  '3D Animation': '三维动画团队',
  '3D Animations': '三维动画团队',
  'Motion Graphic Artist': '动画图形设计师',
  'Motion Graphic Artists': '动画图形设计师',

  // Additional freeform roles (from portfolio QC audit)
  'Agency Producer': '机构制片人',
  'Agency Producers': '机构制片人',
  'Assistant Producer': '助理制片人',
  'Assistant Producers': '助理制片人',
  'Assistant Production Manager': '助理制片经理',
  'Assistant Production Managers': '助理制片经理',
  'BRINC Drone Op': 'BRINC 无人机操作员',
  'BRINC Founder/CEO': 'BRINC 创始人/首席执行官',
  'BRINC Technician': 'BRINC 技术员',
  'BRINC Technicians': 'BRINC 技术员',
  'BRINC VP of Strategy & Marketing Comms': 'BRINC 战略与市场传播副总裁',
  'Best Boy Electric': '电工助理',
  'Best Boy Grip': '场务副手',
  'Camera Assistants': '摄影助理',
  'Camera Assistant': '摄影助理',
  Catering: '餐饮组',
  "Director's Assistant": '导演助理',
  'Food Stylist': '食物造型师',
  'Food Stylists': '食物造型师',
  'Graphic Design': '平面设计',
  'Grip & Lighting': '场务与灯光',
  'Head of Production': '制作总监',
  'Live-Stream Technician': '直播技术员',
  'Live-Stream Technicians': '直播技术员',
  Loader: '装片员',
  Loaders: '装片员',
  Medic: '医护',
  Medics: '医护',
  'Online Editor': 'Online剪辑',
  'Online Editors': 'Online剪辑',
  'Post House': '后期公司',
  'Post Houses': '后期公司',
  'SFX Technician': '特效技术员',
  'SFX Technicians': '特效技术员',
  'Stunt Driver': '特技车手',
  'Stunt Drivers': '特技车手',
  Translator: '翻译',
  Translators: '翻译',
  'Wardrobe Assistant': '造型助理',
  'Wardrobe Assistants': '造型助理',
};
