/**
 * Legacy WordPress ZH URL → current Sanity-backed ZH routes.
 *
 * Generated from migration-data/live-sitemaps/ vs live Sanity slugZh.
 * Sanity slugZh is canonical; these 301s preserve inbound ZH equity.
 *
 * Portfolio CPT path segment was corrected 投资组合 → 案例 (2026-08-03).
 * Sources keep the WP-indexed /zh/投资组合/ prefix; destinations use /zh/案例/.
 * Identity prefix swaps for WP slugs that already matched Sanity are listed
 * after slug-remap rules; a catch-all /zh/投资组合/:slug → /zh/案例/:slug follows.
 *
 * Authoring strings below stay raw Unicode for readability. Exported rules are
 * percent-encoded via encodeRedirectRule for Next.js redirects() matching
 * (vercel/next.js#33470). Do not pre-encode strings in this file.
 *
 * Generated: 2026-07-31; portfolio prefix updated 2026-08-03
 * Rules: 174 (includes catch-all)
 */

import { encodeRedirectRule } from '../../shared/redirect-encoding'

export type LegacyZhRedirect = {
  source: string
  destination: string
  permanent: true
}

const legacyZhRedirectsRaw: LegacyZhRedirect[] = [
  { source: '/zh/产业/车载', destination: '/zh/产业/汽车', permanent: true },
  { source: '/zh/产业/电子学', destination: '/zh/产业/电子产品', permanent: true },
  { source: '/zh/产业/技术', destination: '/zh/产业/科技', permanent: true },
  { source: '/zh/产业/接待', destination: '/zh/产业/酒店与接待', permanent: true },
  { source: '/zh/产业/美容化妆品', destination: '/zh/产业/美容与化妆品', permanent: true },
  { source: '/zh/产业/人工智能机器人', destination: '/zh/产业/人工智能与机器人', permanent: true },
  { source: '/zh/产业/时装', destination: '/zh/产业/时尚', permanent: true },
  { source: '/zh/产业/fmcg', destination: '/zh/产业/快速消费品', permanent: true },
  { source: '/zh/华硕企业版让你升级到不可思议-来自-byron-mckenzie-的活动', destination: '/zh/asus-business-在-byron-mckenzie-指导的广告中邀您-升级至非凡', permanent: true },
  { source: '/zh/类别/按', destination: '/zh/类别/新闻报道', permanent: true },
  { source: '/zh/类别/船员见解', destination: '/zh/类别/团队见解', permanent: true },
  { source: '/zh/类别/幕后', destination: '/zh/类别/幕后花絮', permanent: true },
  { source: '/zh/类别/有创意', destination: '/zh/类别/创意活动', permanent: true },
  { source: '/zh/视频格式/品牌膜', destination: '/zh/视频格式/品牌影片', permanent: true },
  { source: '/zh/投资组合/埃勒瓦纳系列洛伊斯巴保护区野生动物保护区之旅', destination: '/zh/案例/elewana-collection-loisaba-保护区-safari', permanent: true },
  { source: '/zh/投资组合/斑竹实验室涡轮机', destination: '/zh/案例/bambu-lab-vortek-热端更换系统', permanent: true },
  { source: '/zh/投资组合/本-托马斯与-oppo-find-x5-pro-主讲习班', destination: '/zh/案例/oppo-find-x5-pro-本-托马斯大师工坊', permanent: true },
  { source: '/zh/投资组合/博朗-x-大疆', destination: '/zh/案例/博朗-x-大疆-敢于不同', permanent: true },
  { source: '/zh/投资组合/创想三维-x1', destination: '/zh/案例/拓竹-x1-3d打印新先锋', permanent: true },
  { source: '/zh/投资组合/大疆-mavic-2-搭配吉米·辛的滑雪登山', destination: '/zh/案例/大疆御-2-吉米-金的滑雪登山之旅', permanent: true },
  { source: '/zh/投资组合/大疆-osmo-mobile-智能升级', destination: '/zh/案例/大疆灵眸-osmo-mobile-超越智能', permanent: true },
  { source: '/zh/投资组合/大疆禅思x7宣传片', destination: '/zh/案例/大疆-灵眸x7-样片', permanent: true },
  { source: '/zh/投资组合/大疆发布-m200-系列', destination: '/zh/案例/大疆matrice-200', permanent: true },
  { source: '/zh/投资组合/大疆发布-m600', destination: '/zh/案例/大疆-推出悟pro-600', permanent: true },
  { source: '/zh/投资组合/大疆发布幻影-4-pro', destination: '/zh/案例/大疆-phantom-4-pro-隆重发布', permanent: true },
  { source: '/zh/投资组合/大疆故事-澳大利亚海岸线-观看', destination: '/zh/案例/大疆故事-澳大利亚海岸卫士', permanent: true },
  { source: '/zh/投资组合/大疆故事-林肯公园', destination: '/zh/案例/dji的故事-林肯公园', permanent: true },
  { source: '/zh/投资组合/大疆故事-帕瓦瓦岛的座头鲸', destination: '/zh/案例/大疆故事-拉罗汤加的座头鲸', permanent: true },
  { source: '/zh/投资组合/大疆故事-筑梦未来', destination: '/zh/案例/大疆故事-构筑我们的未来', permanent: true },
  { source: '/zh/投资组合/大疆故事-polo-衫', destination: '/zh/案例/大疆故事-polo', permanent: true },
  { source: '/zh/投资组合/大疆故事：马尔代夫地图绘制', destination: '/zh/案例/大疆故事-马尔代夫地图绘制', permanent: true },
  { source: '/zh/投资组合/大疆故事：喂养世界', destination: '/zh/案例/大疆故事-喂养世界', permanent: true },
  { source: '/zh/投资组合/大疆灵眸-osmo-pocket', destination: '/zh/案例/大疆-认识-osmo-pocket', permanent: true },
  { source: '/zh/投资组合/大疆灵眸口袋便携电源', destination: '/zh/案例/大疆灵眸-osmo-pocket-便携动力', permanent: true },
  { source: '/zh/投资组合/大疆灵跃', destination: '/zh/案例/大疆-spark-捕捉你的激情', permanent: true },
  { source: '/zh/投资组合/大疆世界：艾斯奥尔潘的故事', destination: '/zh/案例/大疆世界-艾莎-奥丽的传奇', permanent: true },
  { source: '/zh/投资组合/大疆推出-mavic-2-系列', destination: '/zh/案例/大疆-mavic-2-系列介绍', permanent: true },
  { source: '/zh/投资组合/大疆推出禅思x5系列', destination: '/zh/案例/大疆-zenmuse-x5-系列介绍', permanent: true },
  { source: '/zh/投资组合/大疆推出禅思xt2', destination: '/zh/案例/大疆-推出-zenmuse-xt2', permanent: true },
  { source: '/zh/投资组合/大疆推出禅思z30', destination: '/zh/案例/大疆-推出-zenmuse-z30', permanent: true },
  { source: '/zh/投资组合/大疆推出云台大师摇轮', destination: '/zh/案例/大疆-master-wheels-隆重登场', permanent: true },
  { source: '/zh/投资组合/大疆推出flighthub', destination: '/zh/案例/大疆-flighthub-介绍', permanent: true },
  { source: '/zh/投资组合/大疆晓-钢铁侠', destination: '/zh/案例/tello-钢铁侠限量版-组装完成', permanent: true },
  { source: '/zh/投资组合/大疆御-2-宇宙之旅', destination: '/zh/案例/dji-mavic-2-一次宇宙航行', permanent: true },
  { source: '/zh/投资组合/大疆御-mavic', destination: '/zh/案例/dji-我的御', permanent: true },
  { source: '/zh/投资组合/大疆御-pro-墙到墙艺术', destination: '/zh/案例/大疆-mavic-pro-墙到墙的艺术', permanent: true },
  { source: '/zh/投资组合/大疆遇火花', destination: '/zh/案例/大疆-认识-spark', permanent: true },
  { source: '/zh/投资组合/大疆专访：重新构想婚礼摄影', destination: '/zh/案例/dji-影像预设-婚礼摄影的革新', permanent: true },
  { source: '/zh/投资组合/丰田凯美瑞-2022-极致魅力', destination: '/zh/案例/丰田凯美瑞-2022', permanent: true },
  { source: '/zh/投资组合/富士胶片-jouney-之旅：让更多人享受医疗服务', destination: '/zh/案例/富士胶片-通往更普及医疗的旅程', permanent: true },
  { source: '/zh/投资组合/冈多姆家居-3000', destination: '/zh/案例/gendome-home-3000-您的智能便携式电站', permanent: true },
  { source: '/zh/投资组合/歌飞户外灯，尽享无穷乐趣', destination: '/zh/案例/govee户外灯具乐趣不设限', permanent: true },
  { source: '/zh/投资组合/歌美诗，由歌美诗点亮', destination: '/zh/案例/govee-闪耀由govee点亮', permanent: true },
  { source: '/zh/投资组合/歌诗顿，随心打造居家氛围', destination: '/zh/案例/歌诗顿-随心打造居家氛围', permanent: true },
  { source: '/zh/投资组合/公园无休止地延伸', destination: '/zh/案例/parksible-the-drive-never-ends', permanent: true },
  { source: '/zh/投资组合/哈苏-x1d', destination: '/zh/案例/哈苏-x1d-ii-50c-旅行摄影师', permanent: true },
  { source: '/zh/投资组合/哈苏推出-907x-特别版', destination: '/zh/案例/哈苏-推出-907x-特别版', permanent: true },
  { source: '/zh/投资组合/和发', destination: '/zh/案例/和发冰箱', permanent: true },
  { source: '/zh/投资组合/华硕升级至令人难以置信', destination: '/zh/案例/华硕升级到难以置信', permanent: true },
  { source: '/zh/投资组合/极米-h1', destination: '/zh/案例/xgimi-horizon-pro-让您的视野充满伟岸', permanent: true },
  { source: '/zh/投资组合/匠心独运', destination: '/zh/案例/snapmaker-创造奇迹', permanent: true },
  { source: '/zh/投资组合/杰盛-5000-plus-全屋备用电源', destination: '/zh/案例/jackery-explorer-5000-plus-全屋备用电源', permanent: true },
  { source: '/zh/投资组合/康宝莱', destination: '/zh/案例/康宝莱营养品', permanent: true },
  { source: '/zh/投资组合/科技商业银行-激励-为什么不', destination: '/zh/案例/techcombank-inspire', permanent: true },
  { source: '/zh/投资组合/科隆德尔塔电池发电机', destination: '/zh/案例/ecoflow-delta-电池发电机', permanent: true },
  { source: '/zh/投资组合/老香皂洗发水', destination: '/zh/案例/old-spice-檀香', permanent: true },
  { source: '/zh/投资组合/乐事薯片', destination: '/zh/案例/乐事-max', permanent: true },
  { source: '/zh/投资组合/了解您的激情', destination: '/zh/案例/大疆人物-认识自己的热爱', permanent: true },
  { source: '/zh/投资组合/联合利华，笑容很重要', destination: '/zh/案例/联合利华-微笑很重要', permanent: true },
  { source: '/zh/投资组合/摩普波将告别真空', destination: '/zh/案例/moprobo-one-go-告别吸尘器', permanent: true },
  { source: '/zh/投资组合/佩玛的故事', destination: '/zh/案例/sensoro-佩玛的故事', permanent: true },
  { source: '/zh/投资组合/嵌入式冰箱-空调', destination: '/zh/案例/indwell-双效冰箱与空调', permanent: true },
  { source: '/zh/投资组合/荣耀magic-2', destination: '/zh/案例/荣耀-magic-2-ai', permanent: true },
  { source: '/zh/投资组合/榕树，有更多值得探索的。', destination: '/zh/案例/悦榕庄-发现更多', permanent: true },
  { source: '/zh/投资组合/三星-galaxy-s8-无尽之美-越南', destination: '/zh/案例/三星-galaxy-s8', permanent: true },
  { source: '/zh/投资组合/三星越南-银河-s21', destination: '/zh/案例/三星-galaxy-s21-热门短片', permanent: true },
  { source: '/zh/投资组合/三星x探索', destination: '/zh/案例/三星-x-discovery', permanent: true },
  { source: '/zh/投资组合/石头-h7', destination: '/zh/案例/石头h7系列', permanent: true },
  { source: '/zh/投资组合/石头-q-revo-s-essential-power-ultimate-convenience', destination: '/zh/案例/roborock-qrevo-s-必备动力-极致便捷', permanent: true },
  { source: '/zh/投资组合/石头-s7-maxv-ultra-一切皆轻松', destination: '/zh/案例/石头-s7-maxv-ultra-一切尽在掌握', permanent: true },
  { source: '/zh/投资组合/实现斋月的祝福', destination: '/zh/案例/realme-开斋节的祝福', permanent: true },
  { source: '/zh/投资组合/舒适迪斯科', destination: '/zh/案例/comfort-disco-xin-via', permanent: true },
  { source: '/zh/投资组合/随处像专业人士一样吸烟烤制', destination: '/zh/案例/asmoke-essential-随时随地像专业人士一样烧烤', permanent: true },
  { source: '/zh/投资组合/台湾精品奖-2022', destination: '/zh/案例/台湾精品-2022', permanent: true },
  { source: '/zh/投资组合/泰康人寿手机银行', destination: '/zh/案例/techcombank-手机银行', permanent: true },
  { source: '/zh/投资组合/威斯汀酒店度假村-忙碌-休息', destination: '/zh/案例/威斯汀酒店及度假村-繁忙休憩', permanent: true },
  { source: '/zh/投资组合/维纳牛奶益生菌', destination: '/zh/案例/vinamilk-probi', permanent: true },
  { source: '/zh/投资组合/现代-人类进步', destination: '/zh/案例/现代人类的进步', permanent: true },
  { source: '/zh/投资组合/一加-12-追赶露娜', destination: '/zh/案例/一加-12-追逐月球', permanent: true },
  { source: '/zh/投资组合/一加-8t', destination: '/zh/案例/一加-认识一加-8t', permanent: true },
  { source: '/zh/投资组合/一加-快速-流畅', destination: '/zh/案例/一加-10t-快速流畅', permanent: true },
  { source: '/zh/投资组合/一加-y-系列电视', destination: '/zh/案例/oneplus-y-系列电视-更智能的电视-更明智的选择', permanent: true },
  { source: '/zh/投资组合/一加平板-3，处处精湛', destination: '/zh/案例/一加平板-3-全面掌控', permanent: true },
  { source: '/zh/投资组合/一加与莫汉-德拉维德共创美好时刻', destination: '/zh/案例/oneplus-与莫汉-德拉维德一起创造精彩瞬间', permanent: true },
  { source: '/zh/投资组合/亿蕗净流移动电站', destination: '/zh/案例/ecoflow-river-移动电源站', permanent: true },
  { source: '/zh/投资组合/应对气候变化的新时代', destination: '/zh/案例/brinc-响应的新时代', permanent: true },
  { source: '/zh/投资组合/优利科-空气-10', destination: '/zh/案例/ulike-air-10', permanent: true },
  { source: '/zh/投资组合/御旅行小贴士', destination: '/zh/案例/大疆-mavic-旅行贴士', permanent: true },
  { source: '/zh/投资组合/御迷你', destination: '/zh/案例/大疆-mavic-mini', permanent: true },
  { source: '/zh/投资组合/志云向起重机-m2-打招呼', destination: '/zh/案例/智云-欢迎来到crane-m2', permanent: true },
  { source: '/zh/投资组合/智云畅行-q3', destination: '/zh/案例/智云smooth-q3-照亮创作', permanent: true },
  { source: '/zh/投资组合/智云推出云鹤2s', destination: '/zh/案例/智云-推出云鹤-2s', permanent: true },
  { source: '/zh/投资组合/智云推出云鹤3s', destination: '/zh/案例/智云-crane-3s-震撼发布', permanent: true },
  { source: '/zh/投资组合/智云云鹤3s-稳定器', destination: '/zh/案例/智云-weebill-3s-与-crane-m-3s-便携式视觉叙事-2.0', permanent: true },
  { source: '/zh/投资组合/智云smooth-5，拍出专业电影感', destination: '/zh/案例/智云smooth-5-专业电影拍摄', permanent: true },
  { source: '/zh/投资组合/bambu-lab-h2d-您的个人制造中心', destination: '/zh/案例/拓竹-h2d-您的个人制造中心', permanent: true },
  { source: '/zh/投资组合/bidv-smartbanking-智慧生活', destination: '/zh/案例/bidv-智能银行', permanent: true },
  { source: '/zh/投资组合/bitget-机构交易者', destination: '/zh/案例/bitget-精英交易员', permanent: true },
  { source: '/zh/投资组合/bitget-智能交易', destination: '/zh/案例/bitget-智慧交易', permanent: true },
  { source: '/zh/投资组合/brinc-下一代响应监护人', destination: '/zh/案例/brinc-守护者-下一代响应系统', permanent: true },
  { source: '/zh/投资组合/coca-cola-海洋清理', destination: '/zh/案例/可口可乐-x-海洋清理', permanent: true },
  { source: '/zh/投资组合/dji-故事：切尔诺贝利失落之城', destination: '/zh/案例/大疆故事-切尔诺贝利失落之城', permanent: true },
  { source: '/zh/投资组合/dji-会见机器人大师-s1', destination: '/zh/案例/dji-robomaster-s1', permanent: true },
  { source: '/zh/投资组合/dji-配置文件时间不固定', destination: '/zh/案例/大疆档案-时间是流动的', permanent: true },
  { source: '/zh/投资组合/dji-matrice-200-系列在极端环境中的搜索救援', destination: '/zh/案例/大疆-悟-200-系列-严酷环境下的搜救', permanent: true },
  { source: '/zh/投资组合/dji-mavic-air-地球上最后的狂野之地', destination: '/zh/案例/大疆-mavic-air-地球上最后的净土', permanent: true },
  { source: '/zh/投资组合/dji-osmo-移动宣传活动', destination: '/zh/案例/大疆灵眸视频推广', permanent: true },
  { source: '/zh/投资组合/dji-phantom-4-pro-hawaiian-lava', destination: '/zh/案例/大疆精灵4-pro-夏威夷熔岩', permanent: true },
  { source: '/zh/投资组合/ecoflow-德delta系列，尽享无限生活', destination: '/zh/案例/ecoflow-delta-系列-不受限制的生活', permanent: true },
  { source: '/zh/投资组合/ecoflow-river-600-可定制备用电源', destination: '/zh/案例/ecoflow-river-600-可定制的备用电源', permanent: true },
  { source: '/zh/投资组合/ecoflow-river-mini，电力随行', destination: '/zh/案例/ecoflow-river-mini-触手可及的能量', permanent: true },
  { source: '/zh/投资组合/eflow-wave-保持低温', destination: '/zh/案例/ecoflow-wave-保持凉爽', permanent: true },
  { source: '/zh/投资组合/govee-万圣节', destination: '/zh/案例/govee万圣节', permanent: true },
  { source: '/zh/投资组合/hidock-chatgpt-驱动的音频扩展坞', destination: '/zh/案例/hidock-chatgpt驱动的音频扩展坞', permanent: true },
  { source: '/zh/投资组合/indelb-go20', destination: '/zh/案例/indelb-iceco-go20-拥有不一样的夏天', permanent: true },
  { source: '/zh/投资组合/mammotion-让-luba-2-来完成', destination: '/zh/案例/库犸科技-让-luba-2-来完成', permanent: true },
  { source: '/zh/投资组合/mammotion-luba-2-awd-无线电围栏割草机器人', destination: '/zh/案例/库犸科技-luba-2-awd-无周界电线机器人割草机', permanent: true },
  { source: '/zh/投资组合/mammotion-luba-自动机器人割草机', destination: '/zh/案例/库犸科技-luba-自动化机器人割草机', permanent: true },
  { source: '/zh/投资组合/mammotion-luba-mini-awd-紧凑，强大，准备征服您的草坪', destination: '/zh/案例/mammotion-luba-mini-awd-小巧强劲-征服你的草坪', permanent: true },
  { source: '/zh/投资组合/mammotion-yuka', destination: '/zh/案例/库犸科技-yuka', permanent: true },
  { source: '/zh/投资组合/mammotion-yuka-mini-轻松重新定义草坪养护', destination: '/zh/案例/库犸科技-yuka-mini-轻松重新定义您的草坪养护', permanent: true },
  { source: '/zh/投资组合/mexc-7周年', destination: '/zh/案例/mexc-7周年庆', permanent: true },
  { source: '/zh/投资组合/msi-商务提升日常工作', destination: '/zh/案例/msi-商務-提升日常工作', permanent: true },
  { source: '/zh/投资组合/oppo-reno-7-pro-无限人像', destination: '/zh/案例/oppo-reno-7-pro-无限妈妈-人像模式', permanent: true },
  { source: '/zh/投资组合/petkit-对-purobot-ultra-说你好', destination: '/zh/案例/小佩-向普罗博特ultra问好', permanent: true },
  { source: '/zh/投资组合/realme-15系列5g-每一拍都鲜活真实', destination: '/zh/案例/realme-15-系列-5g-每一拍都真实生动', permanent: true },
  { source: '/zh/投资组合/realme-c75-全方位防护', destination: '/zh/案例/真我-c75-全方位防护', permanent: true },
  { source: '/zh/投资组合/realme-c85-您的终极户外伴侣', destination: '/zh/案例/真我-c85-您的终极户外玩伴', permanent: true },
  { source: '/zh/投资组合/realme-x7-快速-强大', destination: '/zh/案例/真我-x7-快速强大', permanent: true },
  { source: '/zh/投资组合/roborock-s8', destination: '/zh/案例/石头-s8-系列', permanent: true },
  { source: '/zh/投资组合/tpbank-聊天支付', destination: '/zh/案例/tpbank-应用程序', permanent: true },
  { source: '/zh/投资组合/violoop-ai-代理，适用于您的电脑', destination: '/zh/案例/violoop-适用于您PC的AI代理', permanent: true },
  { source: '/zh/投资组合/bitget-getagent-ft-julian-alvarez', destination: '/zh/案例/bitget-getagent-ft-julian-alvarez', permanent: true },
  { source: '/zh/投资组合/govee-永恒户外灯', destination: '/zh/案例/govee-永恒户外灯', permanent: true },
  { source: '/zh/投资组合/insta360-link-人工智能驱动的-4k-网络摄像头', destination: '/zh/案例/insta360-link-人工智能驱动的-4k-网络摄像头', permanent: true },
  { source: '/zh/投资组合/mammotion-luba-3-awd', destination: '/zh/案例/mammotion-luba-3-awd', permanent: true },
  { source: '/zh/投资组合/mammotion-yuka-mini-2', destination: '/zh/案例/mammotion-yuka-mini-2', permanent: true },
  { source: '/zh/投资组合/msi-120hz-perfectedge-显示器', destination: '/zh/案例/msi-120hz-perfectedge-显示器', permanent: true },
  { source: '/zh/投资组合/oppo-reno-6-pro-5g', destination: '/zh/案例/oppo-reno-6-pro-5g', permanent: true },
  { source: '/zh/投资组合/oppo-reno10-pro-5g', destination: '/zh/案例/oppo-reno10-pro-5g', permanent: true },
  { source: '/zh/投资组合/realme-13-5g-释放你的游戏潜能', destination: '/zh/案例/realme-13-5g-释放你的游戏潜能', permanent: true },
  { source: '/zh/投资组合/valerion-visionmaster-max-好莱坞级家庭影院体验', destination: '/zh/案例/valerion-visionmaster-max-好莱坞级家庭影院体验', permanent: true },
  { source: '/zh/投资组合/三星-galaxy-s21', destination: '/zh/案例/三星-galaxy-s21', permanent: true },
  { source: '/zh/投资组合/亚瑟士-dynablast', destination: '/zh/案例/亚瑟士-dynablast', permanent: true },
  { source: '/zh/投资组合/华硕教育-一天的生活', destination: '/zh/案例/华硕教育-一天的生活', permanent: true },
  { source: '/zh/投资组合/大疆-我的香港', destination: '/zh/案例/大疆-我的香港', permanent: true },
  { source: '/zh/投资组合/大疆御-2-快速回顾', destination: '/zh/案例/大疆御-2-快速回顾', permanent: true },
  { source: '/zh/投资组合/爱泉', destination: '/zh/案例/爱泉', permanent: true },
  { source: '/zh/投资组合/突变', destination: '/zh/案例/突变', permanent: true },
  { source: '/zh/投资组合/:slug', destination: '/zh/案例/:slug', permanent: true },
  { source: '/zh/微星利用vantage-pictures为其首部b2b领域全球品牌宣传片', destination: '/zh/微星科技与-vantage-pictures-合作-在-b2b-领域拍摄首部全球品牌宣传片', permanent: true },
  { source: '/zh/我们如何开展史上最成功的众筹活动之一', destination: '/zh/我们如何打造史上最成功的众筹项目之一', permanent: true },
  { source: '/zh/信心十足的每一帧，ulike-活用-vantage-图片，打造幽默美妆', destination: '/zh/每一帧都充满自信：ulike-借助-vantage-pictures-开展幽默美容宣传活动', permanent: true },
  { source: '/zh/与-vantage-pictures-的-alexis-odiowei-进行的导演简介-12-问', destination: '/zh/导演简介：12-个问题问-vantage-pictures-的-alexis-odiowei', permanent: true },
  { source: '/zh/这个跨文化的-oppo-广告为母亲节带来了亟需的怀旧气', destination: '/zh/这支跨文化-oppo-广告为母亲节带来温馨怀旧感', permanent: true },
  { source: '/zh/avantaj-越南-阮仲-谈-越南-制作', destination: '/zh/vantage-pictures-james-duong-谈将中国项目带到越南', permanent: true },
  { source: '/zh/bitget-富有人情味的幽默时刻搅动加密货币交易', destination: '/zh/bitget-以幽默人性化瞬间颠覆加密交易', permanent: true },
  { source: '/zh/bitget-和-vantage-pictures-联手为加密货币交易注入幽默元素', destination: '/zh/bitget-携手-vantage-pictures-为加密交易注入幽默元素', permanent: true },
  { source: '/zh/oneplus-12-的广告宣传彰显逝去的真实影像时代', destination: '/zh/oneplus-12-广告致敬真实影像的黄金时代', permanent: true },
  { source: '/zh/realme-13-5g-沉浸式广告模糊了现实与游戏之间的界限', destination: '/zh/realme-13-5g-沉浸式广告模糊现实与游戏的界限', permanent: true },
  { source: '/zh/realme-发布新款-c75-防意外广告，幽默又混乱', destination: '/zh/realme-推出幽默混乱的全新-c75-防意外-广告', permanent: true },
  { source: '/zh/roborock-对无绳吸尘器进行奇特改造', destination: '/zh/roborock-为无线吸尘器打造别具一格的新形象', permanent: true },
  { source: '/zh/vantage-pictures-为-oneplus-y-系列拍摄电视广告，挖掘内在浪漫情怀', destination: '/zh/vantage-pictures-在-oneplus-y-系列电视广告中捕捉内心浪漫', permanent: true },
  { source: '/zh/vantage-pictures-为一加平板-3-发布推出电影感全球宣传片', destination: '/zh/vantage-pictures-为-oneplus-pad-3-发布会投放电影级全球宣传广告', permanent: true },
]

/** Encoded for Next.js `redirects()` — see shared/redirect-encoding. */
export const legacyZhRedirects: LegacyZhRedirect[] =
  legacyZhRedirectsRaw.map(encodeRedirectRule)
