/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GalleryImageImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "galleryImage.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type TrashRecord = {
  _id: string;
  _type: "trashRecord";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  targetId?: string;
  targetType?: string;
  title?: string;
  trashedAt?: string;
  trashedBy?: string;
  purgeAfter?: string;
  batchId?: string;
  schedule?: {
    releaseId?: string;
    publishAt?: string;
  };
  removedReferences?: Array<{
    referrerId?: string;
    referrerPublishedId?: string;
    referrerType?: string;
    referrerTitle?: string;
    path?: string;
    kind?: "arrayItem" | "arrayReference" | "referenceField";
    itemKey?: string;
    valueJson?: string;
    _key: string;
  }>;
};

export type PortfolioEntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "portfolioEntry";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  excerptZh?: string;
  slug?: Slug;
  slugZh?: Slug;
  showHeroHeader?: boolean;
  heroTitle?: string;
  heroTitleZh?: string;
  noIndex?: boolean;
  seo?: SeoFields;
  heroSlides?: Array<
    {
      _key: string;
    } & PortfolioEntryReference
  >;
  featuredWork?: Array<
    {
      _key: string;
    } & PortfolioEntryReference
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageGallery)
    | ({
        _key: string;
      } & CtaButton)
  >;
  bodyZh?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageGallery)
    | ({
        _key: string;
      } & CtaButton)
  >;
  brandLogos?: Array<
    {
      _key: string;
    } & BrandLogoItem
  >;
  founders?: Array<
    {
      _key: string;
    } & Founder
  >;
  pdfDownload?: PdfDownload;
  trash?: TrashMetadata;
};

export type TrashMetadata = {
  _type: "trashMetadata";
  trashedAt?: string;
  trashedBy?: string;
  purgeAfter?: string;
  batchId?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PdfDownload = {
  _type: "pdfDownload";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  label?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SeoFields = {
  _type: "seoFields";
  metaDescription?: string;
  metaDescriptionZh?: string;
  metaTitle?: string;
  metaTitleZh?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  excerptZh?: string;
  slug?: Slug;
  slugZh?: Slug;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  body?: PortableTextBody;
  bodyZh?: PortableTextBody;
  noIndex?: boolean;
  seo?: SeoFields;
  trash?: TrashMetadata;
};

export type PortableTextBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & VideoEmbed)
>;

export type VideoFormatReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "videoFormat";
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type MarketReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "market";
};

export type ClientReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "client";
};

export type CrewMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "crewMember";
};

export type PlatformReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "platform";
};

export type PortfolioEntry = {
  _id: string;
  _type: "portfolioEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  displayTitleParts?: {
    brandName?: string;
    productName?: string;
    campaignTitle?: string;
    brandNameZh?: string;
    productNameZh?: string;
    campaignTitleZh?: string;
  };
  slug?: Slug;
  slugZh?: Slug;
  publishedAt?: string;
  thumbTitleOverride?: string;
  thumbTitleOverrideZh?: string;
  headerTitleOverride?: string;
  headerTitleOverrideZh?: string;
  longTitleOverride?: string;
  longTitleOverrideZh?: string;
  excerpt?: string;
  excerptZh?: string;
  description?: string;
  descriptionZh?: string;
  videoFormats?: Array<
    {
      _key: string;
    } & VideoFormatReference
  >;
  industries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  markets?: Array<
    {
      _key: string;
    } & MarketReference
  >;
  isHidden?: boolean;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  vimeoUrl?: string;
  xinpianchangUrl?: string;
  heroFilmTitle?: string;
  heroFilmTitleZh?: string;
  additionalVideos?: Array<
    {
      _key: string;
    } & AdditionalVideo
  >;
  clients?: Array<
    {
      _key: string;
    } & ClientReference
  >;
  crewMembers?: Array<
    {
      _key: string;
    } & CrewMemberReference
  >;
  platforms?: Array<
    {
      _key: string;
    } & PlatformReference
  >;
  crewCredits?: Array<
    {
      _key: string;
    } & CrewCredit
  >;
  seo?: SeoFields;
  trash?: TrashMetadata;
};

export type Platform = {
  _id: string;
  _type: "platform";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type TranslatedPhrase = {
  _id: string;
  _type: "translatedPhrase";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  en?: string;
  zh?: string;
  notes?: string;
};

export type CrewMember = {
  _id: string;
  _type: "crewMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: "director" | "dop" | "art-director";
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Market = {
  _id: string;
  _type: "market";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  slug?: Slug;
  slugZh?: Slug;
  description?: string;
  descriptionZh?: string;
  parent?: MarketReference;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  slug?: Slug;
  slugZh?: Slug;
  description?: string;
  descriptionZh?: string;
  parent?: IndustryReference;
};

export type VideoFormat = {
  _id: string;
  _type: "videoFormat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  slug?: Slug;
  slugZh?: Slug;
  description?: string;
  descriptionZh?: string;
  parent?: VideoFormatReference;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleZh?: string;
  slug?: Slug;
  slugZh?: Slug;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail?: string;
  contactPhone?: string;
  contactWhatsapp?: string;
  contactAddress?: string;
  contactAddressZh?: string;
  contactModalTitle?: string;
  contactModalTitleZh?: string;
  contactCtaUrl?: string;
  contactModalIntro?: string;
  contactModalIntroZh?: string;
  contactModalContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  contactModalContentZh?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  contactCtaText?: string;
  contactCtaTextZh?: string;
  legalName?: string;
  foundingDate?: string;
  numberOfEmployees?: {
    minValue?: number;
    maxValue?: number;
  };
  campaignCta?: CampaignCta;
  socialVimeo?: string;
  socialInstagram?: string;
  socialFacebook?: string;
  socialLinkedin?: string;
  socialYoutube?: string;
  socialXinpianchang?: string;
  socialXiaohongshu?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CampaignCta = {
  _type: "campaignCta";
  heading?: string;
  headingZh?: string;
  paragraphs?: Array<string>;
  paragraphsZh?: Array<string>;
  buttonLabel?: string;
  buttonLabelZh?: string;
  buttonHref?: string;
};

export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
  title?: string;
};

export type CtaButton = {
  _type: "ctaButton";
  label?: string;
  url?: string;
};

export type ImageGallery = {
  _type: "imageGallery";
  columns?: number;
  images?: Array<{
    image?: GalleryImageImage;
    alt?: string;
    caption?: string;
    _type: "galleryImage";
    _key: string;
  }>;
};

export type BrandLogoItem = {
  _type: "brandLogoItem";
  logoId?:
    | "aquafina"
    | "asics"
    | "asus"
    | "bambu-lab"
    | "bitget"
    | "braun"
    | "brinc"
    | "cnn"
    | "coca-cola"
    | "dji"
    | "ecoflow"
    | "fujifilm"
    | "govee"
    | "hasselblad"
    | "huawei-horizontal"
    | "huawei-vertical"
    | "hyundai"
    | "insta360"
    | "jackery"
    | "jw-marriott"
    | "msi"
    | "old-spice"
    | "oneplus"
    | "oppo"
    | "p-and-g"
    | "realme"
    | "roborock"
    | "samsung"
    | "taiwan-excellence"
    | "the-north-face"
    | "toyota-horizontal"
    | "toyota-vertical"
    | "unilever"
    | "westin"
    | "youtube"
    | "zhiyun";
};

export type Founder = {
  _type: "founder";
  name?: string;
  jobTitle?: string;
  jobTitleZh?: string;
  professionalTitle?: string;
  professionalTitleZh?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  bioZh?: string;
  sameAs?: Array<string>;
};

export type AdditionalVideo = {
  _type: "additionalVideo";
  vimeoUrl?: string;
  xinpianchangUrl?: string;
  videoTitle?: string;
  videoTitleZh?: string;
  description?: string;
  descriptionZh?: string;
};

export type CrewCredit = {
  _type: "crewCredit";
  department?:
    | "production"
    | "camera"
    | "ge"
    | "art"
    | "casting"
    | "stills"
    | "post";
  isCustomRole?: boolean;
  roleKey?:
    | "brand"
    | "agency"
    | "production_company"
    | "production_service"
    | "ep"
    | "director"
    | "creative_director"
    | "producer"
    | "line_producer"
    | "production_manager"
    | "production_coordinator"
    | "1st_ad"
    | "2nd_ad"
    | "pa"
    | "product_technician"
    | "account_manager"
    | "transport"
    | "chaperone"
    | "bts"
    | "catering"
    | "sound_recordist"
    | "dop"
    | "camera_op"
    | "steadicam_op"
    | "1st_ac"
    | "2nd_ac"
    | "focus_puller"
    | "camera_assistants"
    | "dit"
    | "qtake"
    | "drone_op"
    | "motion_control"
    | "rental_house"
    | "gaffer"
    | "key_grip"
    | "grip"
    | "electrician"
    | "production_designer"
    | "art_director"
    | "art_assistant"
    | "props_master"
    | "wardrobe"
    | "wardrobe_assistant"
    | "hair_makeup"
    | "location_manager"
    | "storyboards"
    | "casting_director"
    | "casting_manager"
    | "talent"
    | "stunt_coordinator"
    | "choreographer"
    | "animal_wrangler"
    | "photographer"
    | "photography_producer"
    | "kv_art_director"
    | "photography_assistant"
    | "photo_talent"
    | "post_supervisor"
    | "post_house"
    | "on_set_editor"
    | "editor"
    | "assistant_editors"
    | "colorist"
    | "sound_design_mix"
    | "composer"
    | "voice_over"
    | "vfx"
    | "online"
    | "motion_graphics"
    | "3d_animation";
  role?: string;
  people?: Array<
    {
      _key: string;
    } & CrewPerson
  >;
};

export type CreditIdentityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "creditIdentity";
};

export type CrewPerson = {
  _type: "crewPerson";
  identity?: CreditIdentityReference;
  name?: string;
  url?: string;
  linkTitle?: string;
};

export type CreditIdentity = {
  _id: string;
  _type: "creditIdentity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  nameZh?: string;
  url?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | GalleryImageImage
  | TrashRecord
  | PortfolioEntryReference
  | Page
  | TrashMetadata
  | SanityFileAssetReference
  | PdfDownload
  | SanityImageCrop
  | SanityImageHotspot
  | SeoFields
  | Slug
  | CategoryReference
  | BlogPost
  | PortableTextBody
  | VideoFormatReference
  | IndustryReference
  | MarketReference
  | ClientReference
  | CrewMemberReference
  | PlatformReference
  | PortfolioEntry
  | Platform
  | TranslatedPhrase
  | CrewMember
  | Client
  | Market
  | Industry
  | VideoFormat
  | Category
  | SiteSettings
  | CampaignCta
  | VideoEmbed
  | CtaButton
  | ImageGallery
  | BrandLogoItem
  | Founder
  | AdditionalVideo
  | CrewCredit
  | CreditIdentityReference
  | CrewPerson
  | CreditIdentity
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries/blog.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "blogPost" && !defined(trash.trashedAt) && (    slug.current == $slug || slugZh.current == $slug  )][0]{    _id,    title,    titleZh,    "slug": slug.current,    "slugZh": slugZh.current,    _createdAt,    _updatedAt,    featuredImage,    excerpt,    excerptZh,    body,    bodyZh,    "categories": categories[]->{      _id,      title,      titleZh,      "slug": slug.current,      "slugZh": slugZh.current    },    noIndex,    seo{      metaDescription,      metaDescriptionZh,      metaTitle,      metaTitleZh,      ogImage    }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  titleZh: string | null;
  slug: string | null;
  slugZh: string | null;
  _createdAt: string;
  _updatedAt: string;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  excerpt: string | null;
  excerptZh: string | null;
  body: PortableTextBody | null;
  bodyZh: PortableTextBody | null;
  categories: Array<{
    _id: string;
    title: string | null;
    titleZh: string | null;
    slug: string | null;
    slugZh: string | null;
  }> | null;
  noIndex: boolean | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "home" && !defined(trash.trashedAt)][0]{      _id,  title,  titleZh,  "slug": slug.current,  "slugZh": slugZh.current,  showHeroHeader,  heroTitle,  heroTitleZh,  featuredImage,  body,  bodyZh,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex,    "heroSlides": heroSlides[      !defined(@->trash.trashedAt)    ]->{        "slug": slug.current,  "slugZh": slugZh.current,  displayTitleParts{    brandName,    productName,    campaignTitle,    brandNameZh,    productNameZh,    campaignTitleZh  },  headerTitleOverride,  headerTitleOverrideZh,  "description": coalesce(excerpt, seo.metaDescription),  "descriptionZh": coalesce(excerptZh, seo.metaDescriptionZh),  featuredImage    },    "featuredWork": featuredWork[      !defined(@->trash.trashedAt) && @->isHidden != true    ]->{        _id,  "slug": slug.current,  "slugZh": slugZh.current,  displayTitleParts{    brandName,    productName,    campaignTitle,    brandNameZh,    productNameZh,    campaignTitleZh  },  thumbTitleOverride,  thumbTitleOverrideZh,  featuredImage,  isHidden    },    brandLogos[]{      logoId    }  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  titleZh: string | null;
  slug: string | null;
  slugZh: string | null;
  showHeroHeader: boolean | null;
  heroTitle: string | null;
  heroTitleZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  bodyZh: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
  heroSlides: Array<{
    slug: string | null;
    slugZh: string | null;
    displayTitleParts: {
      brandName: string | null;
      productName: string | null;
      campaignTitle: string | null;
      brandNameZh: string | null;
      productNameZh: string | null;
      campaignTitleZh: string | null;
    } | null;
    headerTitleOverride: string | null;
    headerTitleOverrideZh: string | null;
    description: string | null;
    descriptionZh: string | null;
    featuredImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
  featuredWork: Array<{
    _id: string;
    slug: string | null;
    slugZh: string | null;
    displayTitleParts: {
      brandName: string | null;
      productName: string | null;
      campaignTitle: string | null;
      brandNameZh: string | null;
      productNameZh: string | null;
      campaignTitleZh: string | null;
    } | null;
    thumbTitleOverride: string | null;
    thumbTitleOverrideZh: string | null;
    featuredImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    isHidden: boolean | null;
  }> | null;
  brandLogos: Array<{
    logoId:
      | "aquafina"
      | "asics"
      | "asus"
      | "bambu-lab"
      | "bitget"
      | "braun"
      | "brinc"
      | "cnn"
      | "coca-cola"
      | "dji"
      | "ecoflow"
      | "fujifilm"
      | "govee"
      | "hasselblad"
      | "huawei-horizontal"
      | "huawei-vertical"
      | "hyundai"
      | "insta360"
      | "jackery"
      | "jw-marriott"
      | "msi"
      | "old-spice"
      | "oneplus"
      | "oppo"
      | "p-and-g"
      | "realme"
      | "roborock"
      | "samsung"
      | "taiwan-excellence"
      | "the-north-face"
      | "toyota-horizontal"
      | "toyota-vertical"
      | "unilever"
      | "westin"
      | "youtube"
      | "zhiyun"
      | null;
  }> | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "about" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex,      heroTitle,  heroTitleZh,  body,  bodyZh,    founders[]{      name,      jobTitle,      jobTitleZh,      professionalTitle,      professionalTitleZh,      image,      bio,      bioZh,      sameAs    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
  heroTitle: string | null;
  heroTitleZh: string | null;
  body: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  bodyZh: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  founders: Array<{
    name: string | null;
    jobTitle: string | null;
    jobTitleZh: string | null;
    professionalTitle: string | null;
    professionalTitleZh: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    bioZh: string | null;
    sameAs: Array<string> | null;
  }> | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "contact" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex  }
export type CONTACT_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: NEWS_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "news" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex,      heroTitle,  heroTitleZh,  body,  bodyZh  }
export type NEWS_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
  heroTitle: string | null;
  heroTitleZh: string | null;
  body: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  bodyZh: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: VIETNAM_LOCATION_GUIDE_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "vietnam-location-guide" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex,      heroTitle,  heroTitleZh,  body,  bodyZh,    pdfDownload{      label,      file{        asset->{          _id,          url        }      }    }  }
export type VIETNAM_LOCATION_GUIDE_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
  heroTitle: string | null;
  heroTitleZh: string | null;
  body: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  bodyZh: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  pdfDownload: {
    label: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: VIETNAM_PRODUCTION_SERVICE_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "vietnam-production-service" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex,      heroTitle,  heroTitleZh,  body,  bodyZh,    "featuredWork": featuredWork[      !defined(@->trash.trashedAt) && @->isHidden != true    ]->{        _id,  "slug": slug.current,  "slugZh": slugZh.current,  displayTitleParts{    brandName,    productName,    campaignTitle,    brandNameZh,    productNameZh,    campaignTitleZh  },  thumbTitleOverride,  thumbTitleOverrideZh,  featuredImage,  isHidden    }  }
export type VIETNAM_PRODUCTION_SERVICE_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
  heroTitle: string | null;
  heroTitleZh: string | null;
  body: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  bodyZh: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  featuredWork: Array<{
    _id: string;
    slug: string | null;
    slugZh: string | null;
    displayTitleParts: {
      brandName: string | null;
      productName: string | null;
      campaignTitle: string | null;
      brandNameZh: string | null;
      productNameZh: string | null;
      campaignTitleZh: string | null;
    } | null;
    thumbTitleOverride: string | null;
    thumbTitleOverrideZh: string | null;
    featuredImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    isHidden: boolean | null;
  }> | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: WORK_PAGE_META_QUERY
// Query: *[_type == "page" && slug.current == "work" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex  }
export type WORK_PAGE_META_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
} | null;

// Source: ../src/sanity/queries/pages.ts
// Variable: VIDEO_CAMPAIGN_BRIEF_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "video-campaign-brief" && !defined(trash.trashedAt)][0]{      title,  titleZh,  "slugZh": slugZh.current,  featuredImage,  seo{    metaDescription,    metaDescriptionZh,    metaTitle,    metaTitleZh,    ogImage  },  noIndex  }
export type VIDEO_CAMPAIGN_BRIEF_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  slugZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  noIndex: boolean | null;
} | null;

// Source: ../src/sanity/queries/portfolio.ts
// Variable: PORTFOLIO_ENTRY_QUERY
// Query: *[_type == "portfolioEntry" && !defined(trash.trashedAt) && (    slug.current == $slug || slugZh.current == $slug  )][0]{    _id,    title,    titleZh,    "slug": slug.current,    "slugZh": slugZh.current,      displayTitleParts{    brandName,    productName,    campaignTitle,    brandNameZh,    productNameZh,    campaignTitleZh  },  heroFilmTitle,  heroFilmTitleZh,  thumbTitleOverride,  thumbTitleOverrideZh,  headerTitleOverride,  headerTitleOverrideZh,  longTitleOverride,  longTitleOverrideZh,    excerpt,    excerptZh,    description,    descriptionZh,    featuredImage,    vimeoUrl,    xinpianchangUrl,    publishedAt,    isHidden,    additionalVideos[]{      vimeoUrl,      xinpianchangUrl,      videoTitle,      videoTitleZh,      description,      descriptionZh    },      crewCredits[]{    _key,    department,    roleKey,    role,    isCustomRole,    people[]{      _key,      name,      "url": coalesce(identity->url, url),      linkTitle,      "identityId": identity._ref,      "identityName": identity->name,      "identityNameZh": identity->nameZh    }  },    seo{      metaDescription,      metaDescriptionZh,      metaTitle,      metaTitleZh,      ogImage    }  }
export type PORTFOLIO_ENTRY_QUERY_RESULT = {
  _id: string;
  title: string | null;
  titleZh: string | null;
  slug: string | null;
  slugZh: string | null;
  displayTitleParts: {
    brandName: string | null;
    productName: string | null;
    campaignTitle: string | null;
    brandNameZh: string | null;
    productNameZh: string | null;
    campaignTitleZh: string | null;
  } | null;
  heroFilmTitle: string | null;
  heroFilmTitleZh: string | null;
  thumbTitleOverride: string | null;
  thumbTitleOverrideZh: string | null;
  headerTitleOverride: string | null;
  headerTitleOverrideZh: string | null;
  longTitleOverride: string | null;
  longTitleOverrideZh: string | null;
  excerpt: string | null;
  excerptZh: string | null;
  description: string | null;
  descriptionZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  vimeoUrl: string | null;
  xinpianchangUrl: string | null;
  publishedAt: string | null;
  isHidden: boolean | null;
  additionalVideos: Array<{
    vimeoUrl: string | null;
    xinpianchangUrl: string | null;
    videoTitle: string | null;
    videoTitleZh: string | null;
    description: string | null;
    descriptionZh: string | null;
  }> | null;
  crewCredits: Array<{
    _key: string;
    department:
      | "art"
      | "camera"
      | "casting"
      | "ge"
      | "post"
      | "production"
      | "stills"
      | null;
    roleKey:
      | "1st_ac"
      | "1st_ad"
      | "2nd_ac"
      | "2nd_ad"
      | "3d_animation"
      | "account_manager"
      | "agency"
      | "animal_wrangler"
      | "art_assistant"
      | "art_director"
      | "assistant_editors"
      | "brand"
      | "bts"
      | "camera_assistants"
      | "camera_op"
      | "casting_director"
      | "casting_manager"
      | "catering"
      | "chaperone"
      | "choreographer"
      | "colorist"
      | "composer"
      | "creative_director"
      | "director"
      | "dit"
      | "dop"
      | "drone_op"
      | "editor"
      | "electrician"
      | "ep"
      | "focus_puller"
      | "gaffer"
      | "grip"
      | "hair_makeup"
      | "key_grip"
      | "kv_art_director"
      | "line_producer"
      | "location_manager"
      | "motion_control"
      | "motion_graphics"
      | "on_set_editor"
      | "online"
      | "pa"
      | "photo_talent"
      | "photographer"
      | "photography_assistant"
      | "photography_producer"
      | "post_house"
      | "post_supervisor"
      | "producer"
      | "product_technician"
      | "production_company"
      | "production_coordinator"
      | "production_designer"
      | "production_manager"
      | "production_service"
      | "props_master"
      | "qtake"
      | "rental_house"
      | "sound_design_mix"
      | "sound_recordist"
      | "steadicam_op"
      | "storyboards"
      | "stunt_coordinator"
      | "talent"
      | "transport"
      | "vfx"
      | "voice_over"
      | "wardrobe_assistant"
      | "wardrobe"
      | null;
    role: string | null;
    isCustomRole: boolean | null;
    people: Array<{
      _key: string;
      name: string | null;
      url: string | null;
      linkTitle: string | null;
      identityId: string | null;
      identityName: string | null;
      identityNameZh: string | null;
    }> | null;
  }> | null;
  seo: {
    metaDescription: string | null;
    metaDescriptionZh: string | null;
    metaTitle: string | null;
    metaTitleZh: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../src/sanity/queries/portfolio.ts
// Variable: WORK_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "work" && !defined(trash.trashedAt)][0]{    title,    titleZh,    heroTitle,    heroTitleZh,    featuredImage,    body,    bodyZh  }
export type WORK_PAGE_QUERY_RESULT = {
  title: string | null;
  titleZh: string | null;
  heroTitle: string | null;
  heroTitleZh: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  bodyZh: Array<
    | ({
        _key: string;
      } & CtaButton)
    | ({
        _key: string;
      } & ImageGallery)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blogPost" && !defined(trash.trashedAt) && (\n    slug.current == $slug || slugZh.current == $slug\n  )][0]{\n    _id,\n    title,\n    titleZh,\n    "slug": slug.current,\n    "slugZh": slugZh.current,\n    _createdAt,\n    _updatedAt,\n    featuredImage,\n    excerpt,\n    excerptZh,\n    body,\n    bodyZh,\n    "categories": categories[]->{\n      _id,\n      title,\n      titleZh,\n      "slug": slug.current,\n      "slugZh": slugZh.current\n    },\n    noIndex,\n    seo{\n      metaDescription,\n      metaDescriptionZh,\n      metaTitle,\n      metaTitleZh,\n      ogImage\n    }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "home" && !defined(trash.trashedAt)][0]{\n    \n  _id,\n  title,\n  titleZh,\n  "slug": slug.current,\n  "slugZh": slugZh.current,\n  showHeroHeader,\n  heroTitle,\n  heroTitleZh,\n  featuredImage,\n  body,\n  bodyZh,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n,\n    "heroSlides": heroSlides[\n      !defined(@->trash.trashedAt)\n    ]->{\n      \n  "slug": slug.current,\n  "slugZh": slugZh.current,\n  displayTitleParts{\n    brandName,\n    productName,\n    campaignTitle,\n    brandNameZh,\n    productNameZh,\n    campaignTitleZh\n  },\n  headerTitleOverride,\n  headerTitleOverrideZh,\n  "description": coalesce(excerpt, seo.metaDescription),\n  "descriptionZh": coalesce(excerptZh, seo.metaDescriptionZh),\n  featuredImage\n\n    },\n    "featuredWork": featuredWork[\n      !defined(@->trash.trashedAt) && @->isHidden != true\n    ]->{\n      \n  _id,\n  "slug": slug.current,\n  "slugZh": slugZh.current,\n  displayTitleParts{\n    brandName,\n    productName,\n    campaignTitle,\n    brandNameZh,\n    productNameZh,\n    campaignTitleZh\n  },\n  thumbTitleOverride,\n  thumbTitleOverrideZh,\n  featuredImage,\n  isHidden\n\n    },\n    brandLogos[]{\n      logoId\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "about" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n,\n    \n  heroTitle,\n  heroTitleZh,\n  body,\n  bodyZh\n,\n    founders[]{\n      name,\n      jobTitle,\n      jobTitleZh,\n      professionalTitle,\n      professionalTitleZh,\n      image,\n      bio,\n      bioZh,\n      sameAs\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "contact" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "news" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n,\n    \n  heroTitle,\n  heroTitleZh,\n  body,\n  bodyZh\n\n  }\n': NEWS_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "vietnam-location-guide" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n,\n    \n  heroTitle,\n  heroTitleZh,\n  body,\n  bodyZh\n,\n    pdfDownload{\n      label,\n      file{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  }\n': VIETNAM_LOCATION_GUIDE_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "vietnam-production-service" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n,\n    \n  heroTitle,\n  heroTitleZh,\n  body,\n  bodyZh\n,\n    "featuredWork": featuredWork[\n      !defined(@->trash.trashedAt) && @->isHidden != true\n    ]->{\n      \n  _id,\n  "slug": slug.current,\n  "slugZh": slugZh.current,\n  displayTitleParts{\n    brandName,\n    productName,\n    campaignTitle,\n    brandNameZh,\n    productNameZh,\n    campaignTitleZh\n  },\n  thumbTitleOverride,\n  thumbTitleOverrideZh,\n  featuredImage,\n  isHidden\n\n    }\n  }\n': VIETNAM_PRODUCTION_SERVICE_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "work" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n\n  }\n': WORK_PAGE_META_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "video-campaign-brief" && !defined(trash.trashedAt)][0]{\n    \n  title,\n  titleZh,\n  "slugZh": slugZh.current,\n  featuredImage,\n  seo{\n    metaDescription,\n    metaDescriptionZh,\n    metaTitle,\n    metaTitleZh,\n    ogImage\n  },\n  noIndex\n\n  }\n': VIDEO_CAMPAIGN_BRIEF_PAGE_QUERY_RESULT;
    '\n  *[_type == "portfolioEntry" && !defined(trash.trashedAt) && (\n    slug.current == $slug || slugZh.current == $slug\n  )][0]{\n    _id,\n    title,\n    titleZh,\n    "slug": slug.current,\n    "slugZh": slugZh.current,\n    \n  displayTitleParts{\n    brandName,\n    productName,\n    campaignTitle,\n    brandNameZh,\n    productNameZh,\n    campaignTitleZh\n  },\n  heroFilmTitle,\n  heroFilmTitleZh,\n  thumbTitleOverride,\n  thumbTitleOverrideZh,\n  headerTitleOverride,\n  headerTitleOverrideZh,\n  longTitleOverride,\n  longTitleOverrideZh\n,\n    excerpt,\n    excerptZh,\n    description,\n    descriptionZh,\n    featuredImage,\n    vimeoUrl,\n    xinpianchangUrl,\n    publishedAt,\n    isHidden,\n    additionalVideos[]{\n      vimeoUrl,\n      xinpianchangUrl,\n      videoTitle,\n      videoTitleZh,\n      description,\n      descriptionZh\n    },\n    \n  crewCredits[]{\n    _key,\n    department,\n    roleKey,\n    role,\n    isCustomRole,\n    people[]{\n      _key,\n      name,\n      "url": coalesce(identity->url, url),\n      linkTitle,\n      "identityId": identity._ref,\n      "identityName": identity->name,\n      "identityNameZh": identity->nameZh\n    }\n  }\n,\n    seo{\n      metaDescription,\n      metaDescriptionZh,\n      metaTitle,\n      metaTitleZh,\n      ogImage\n    }\n  }\n': PORTFOLIO_ENTRY_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == "work" && !defined(trash.trashedAt)][0]{\n    title,\n    titleZh,\n    heroTitle,\n    heroTitleZh,\n    featuredImage,\n    body,\n    bodyZh\n  }\n': WORK_PAGE_QUERY_RESULT;
  }
}
