<?php
/**
 * Single Portfolio Item
 * File: single-portfolio.php
 * Post type: portfolio
 */

get_header();

if (!function_exists('vp_portfolio_get')) {
  function vp_portfolio_get($key, $post_id = null) {
    $post_id = $post_id ?: get_the_ID();
    if (function_exists('get_field')) return get_field($key, $post_id);
    return get_post_meta($post_id, $key, true);
  }
}

if (!function_exists('vp_portfolio_header_title')) {
  function vp_portfolio_header_title($post_id = null) {
    $t = trim((string) vp_portfolio_get('header_title', $post_id));
    return $t !== '' ? $t : get_the_title($post_id ?: get_the_ID());
  }
}
if (!function_exists('vp_portfolio_long_title')) {
  function vp_portfolio_long_title($post_id = null) {
    $t = trim((string) vp_portfolio_get('long_title', $post_id));
    return $t !== '' ? $t : get_the_title($post_id ?: get_the_ID());
  }
}

$post_id = get_the_ID();

$vimeo = vp_portfolio_get('vimeo_link', $post_id);         // oEmbed
$desc  = vp_portfolio_get('description', $post_id);        // textarea

$hero_bg = get_the_post_thumbnail_url($post_id, 'full');
$hero_style = $hero_bg ? 'style="background-image:url(' . esc_url($hero_bg) . ');"' : '';
?>

<?php while (have_posts()) : the_post(); ?>

  <header class="vp-page-hero" <?php echo $hero_style; ?>>
    <div class="vp-page-hero__overlay"></div>
    <div class="container vp-page-hero__inner">
      <h1 class="vp-page-hero__title mb-0">
        <?php
        $hero_title = vp_portfolio_header_title($post_id);

        echo wp_kses(
          $hero_title,
          [
            'span' => ['class' => true],
            'br'   => [],
          ]
        );
        ?>
      </h1>
    </div>
  </header>

  <!-- Main -->
  <section class="vp-section py-5">
    <div class="container-fluid">
      <div class="row g-4">

        <!-- Left: Title + Description + Credits -->
        <div class="col-12 offset-lg-1 col-lg-3 order-2 order-lg-1">
          <h2 class="mb-3">
            <?php
            echo wp_kses(
              vp_portfolio_long_title($post_id),
              [
                'span' => ['class' => true],
                'br'   => [],
              ]
            );
            ?></h2>

          <?php if (!empty($desc)) : ?>
            <div class="text-body-secondary mb-4">
              <?php echo wp_kses_post(wpautop($desc)); ?>
            </div>
          <?php endif; ?>

        </div>

        <!-- Right: Vimeo -->
        <div class="col-12 col-lg-7 order-1 order-lg-2">
          <?php if (!empty($vimeo)) : ?>
            <div class="ratio ratio-16x9 mb-3">
              <?php
                $vimeo_raw = trim((string) $vimeo);

                // If ACF field is an oEmbed field, it might already be an iframe HTML string.
                if (stripos($vimeo_raw, '<iframe') !== false) {

                  echo wp_kses($vimeo_raw, [
                    'iframe' => [
                      'src'             => true,
                      'width'           => true,
                      'height'          => true,
                      'frameborder'     => true,
                      'allow'           => true,
                      'allowfullscreen' => true,
                      'title'           => true,
                      'loading'         => true,
                      'referrerpolicy'  => true,
                    ],
                  ]);

                } else {

                  // Otherwise treat it as a URL and ask WP to generate the embed.
                  $embed = wp_oembed_get($vimeo_raw);

                  if ($embed) {
                    echo $embed; // already safe HTML generated by WP
                  } else {
                    echo '<div class="bg-dark text-white-50 p-4 rounded">Invalid video link.</div>';
                  }

                }
              ?>
            </div>
            
            <?php if (function_exists('vp_portfolio_render_credits')) : ?>
              <?php vp_portfolio_render_credits($post_id); ?>
            <?php endif; ?>

          <?php else : ?>
            <div class="bg-dark text-white-50 p-4 rounded">
              No video embed found for this portfolio item.
            </div>
          <?php endif; ?>
        </div>

      </div>
    </div>
  </section>

<?php endwhile; ?>

<?php
$prev = vp_portfolio_adjacent('prev', 'video-format'); // same format
$next = vp_portfolio_adjacent('next', 'video-format'); // same format
?>

<?php if ($prev || $next) : ?>
  <section class="vp-section py-5 border-top">
    <div class="container">
      <div class="row g-3 g-md-4">

        <div class="col-12 col-md-6">
          <?php if ($prev) : ?>
            <a class="d-block text-decoration-none" href="<?php echo esc_url(get_permalink($prev)); ?>">
              <div class="text-uppercase text-body-secondary fw-semibold mb-2" style="letter-spacing:.08em;font-size:.75rem;">
                Previous
              </div>

              <div class="ratio ratio-16x9 overflow-hidden bg-dark">
                <?php echo get_the_post_thumbnail($prev->ID, 'large', [
                  'class' => 'w-100 h-100 object-fit-cover',
                  'loading' => 'lazy',
                  'alt' => esc_attr(get_the_title($prev)),
                ]); ?>
              </div>

              <div class="mt-2 fw-semibold text-white">
                <?php echo esc_html(function_exists('vp_portfolio_thumb_title') ? vp_portfolio_thumb_title($prev->ID) : get_the_title($prev)); ?>
              </div>
            </a>
          <?php endif; ?>
        </div>

        <div class="col-12 col-md-6 text-md-end">
          <?php if ($next) : ?>
            <a class="d-block text-decoration-none" href="<?php echo esc_url(get_permalink($next)); ?>">
              <div class="text-uppercase text-body-secondary fw-semibold mb-2" style="letter-spacing:.08em;font-size:.75rem;">
                Next
              </div>

              <div class="ratio ratio-16x9 overflow-hidden bg-dark">
                <?php echo get_the_post_thumbnail($next->ID, 'large', [
                  'class' => 'w-100 h-100 object-fit-cover',
                  'loading' => 'lazy',
                  'alt' => esc_attr(get_the_title($next)),
                ]); ?>
              </div>

              <div class="mt-2 fw-semibold text-white">
                <?php echo esc_html(function_exists('vp_portfolio_thumb_title') ? vp_portfolio_thumb_title($next->ID) : get_the_title($next)); ?>
              </div>
            </a>
          <?php endif; ?>
        </div>

      </div>
    </div>
  </section>
<?php endif; ?>

<?php get_footer(); ?>