/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type GalleryImageImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type TrashRecord = {
  _id: string
  _type: 'trashRecord'
  _createdAt: string
  _updatedAt: string
  _rev: string
  targetId?: string
  targetType?: string
  title?: string
  trashedAt?: string
  trashedBy?: string
  purgeAfter?: string
  batchId?: string
  schedule?: {
    releaseId?: string
    publishAt?: string
  }
  removedReferences?: Array<{
    referrerId?: string
    referrerPublishedId?: string
    referrerType?: string
    referrerTitle?: string
    path?: string
    kind?: 'arrayItem' | 'arrayReference' | 'referenceField'
    itemKey?: string
    valueJson?: string
    _key: string
  }>
}

export type PortfolioEntryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'portfolioEntry'
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  featuredImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  excerpt?: string
  excerptZh?: string
  slug?: Slug
  slugZh?: Slug
  showHeroHeader?: boolean
  heroTitle?: string
  heroTitleZh?: string
  noIndex?: boolean
  seo?: SeoFields
  heroSlides?: Array<
    {
      _key: string
    } & PortfolioEntryReference
  >
  featuredWork?: Array<
    {
      _key: string
    } & PortfolioEntryReference
  >
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & ImageGallery)
    | ({
        _key: string
      } & CtaButton)
  >
  bodyZh?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & ImageGallery)
    | ({
        _key: string
      } & CtaButton)
  >
  brandLogos?: Array<
    {
      _key: string
    } & BrandLogoItem
  >
  founders?: Array<
    {
      _key: string
    } & Founder
  >
  pdfDownload?: PdfDownload
  trash?: TrashMetadata
}

export type TrashMetadata = {
  _type: 'trashMetadata'
  trashedAt?: string
  trashedBy?: string
  purgeAfter?: string
  batchId?: string
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type PdfDownload = {
  _type: 'pdfDownload'
  file?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  label?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SeoFields = {
  _type: 'seoFields'
  metaDescription?: string
  metaDescriptionZh?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  featuredImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  excerpt?: string
  excerptZh?: string
  slug?: Slug
  slugZh?: Slug
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  body?: PortableTextBody
  bodyZh?: PortableTextBody
  seo?: SeoFields
  trash?: TrashMetadata
}

export type PortableTextBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & VideoEmbed)
>

export type VideoFormatReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'videoFormat'
}

export type IndustryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'industry'
}

export type MarketReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'market'
}

export type ClientReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'client'
}

export type CrewMemberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'crewMember'
}

export type PlatformReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'platform'
}

export type PortfolioEntry = {
  _id: string
  _type: 'portfolioEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  displayTitleParts?: {
    brandName?: string
    productName?: string
    campaignTitle?: string
    brandNameZh?: string
    productNameZh?: string
    campaignTitleZh?: string
  }
  slug?: Slug
  slugZh?: Slug
  publishedAt?: string
  thumbTitleOverride?: string
  thumbTitleOverrideZh?: string
  headerTitleOverride?: string
  headerTitleOverrideZh?: string
  longTitleOverride?: string
  longTitleOverrideZh?: string
  excerpt?: string
  excerptZh?: string
  description?: string
  descriptionZh?: string
  videoFormats?: Array<
    {
      _key: string
    } & VideoFormatReference
  >
  industries?: Array<
    {
      _key: string
    } & IndustryReference
  >
  markets?: Array<
    {
      _key: string
    } & MarketReference
  >
  isHidden?: boolean
  featuredImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  vimeoUrl?: string
  xinpianchangUrl?: string
  heroFilmTitle?: string
  heroFilmTitleZh?: string
  additionalVideos?: Array<
    {
      _key: string
    } & AdditionalVideo
  >
  clients?: Array<
    {
      _key: string
    } & ClientReference
  >
  crewMembers?: Array<
    {
      _key: string
    } & CrewMemberReference
  >
  platforms?: Array<
    {
      _key: string
    } & PlatformReference
  >
  crewCredits?: Array<
    {
      _key: string
    } & CrewCredit
  >
  seo?: SeoFields
  trash?: TrashMetadata
}

export type Platform = {
  _id: string
  _type: 'platform'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
}

export type TranslatedPhrase = {
  _id: string
  _type: 'translatedPhrase'
  _createdAt: string
  _updatedAt: string
  _rev: string
  en?: string
  zh?: string
  notes?: string
}

export type CrewMember = {
  _id: string
  _type: 'crewMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  role?: 'director' | 'dop' | 'art-director'
}

export type Client = {
  _id: string
  _type: 'client'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
}

export type Market = {
  _id: string
  _type: 'market'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  slug?: Slug
  slugZh?: Slug
  description?: string
  descriptionZh?: string
  parent?: MarketReference
}

export type Industry = {
  _id: string
  _type: 'industry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  slug?: Slug
  slugZh?: Slug
  description?: string
  descriptionZh?: string
  parent?: IndustryReference
}

export type VideoFormat = {
  _id: string
  _type: 'videoFormat'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  slug?: Slug
  slugZh?: Slug
  description?: string
  descriptionZh?: string
  parent?: VideoFormatReference
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleZh?: string
  slug?: Slug
  slugZh?: Slug
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  contactEmail?: string
  contactPhone?: string
  contactWhatsapp?: string
  contactAddress?: string
  contactAddressZh?: string
  contactModalTitle?: string
  contactModalTitleZh?: string
  contactModalIntro?: string
  contactModalIntroZh?: string
  contactModalContent?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  contactModalContentZh?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  contactCtaText?: string
  contactCtaTextZh?: string
  contactCtaUrl?: string
  campaignCta?: CampaignCta
  socialVimeo?: string
  socialInstagram?: string
  socialFacebook?: string
  socialLinkedin?: string
  socialYoutube?: string
  socialXinpianchang?: string
  socialXiaohongshu?: string
  defaultOgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type CampaignCta = {
  _type: 'campaignCta'
  heading?: string
  headingZh?: string
  paragraphs?: Array<string>
  paragraphsZh?: Array<string>
  buttonLabel?: string
  buttonLabelZh?: string
  buttonHref?: string
}

export type VideoEmbed = {
  _type: 'videoEmbed'
  url?: string
  title?: string
}

export type CtaButton = {
  _type: 'ctaButton'
  label?: string
  url?: string
}

export type ImageGallery = {
  _type: 'imageGallery'
  columns?: number
  images?: Array<{
    image?: GalleryImageImage
    alt?: string
    caption?: string
    _type: 'galleryImage'
    _key: string
  }>
}

export type BrandLogoItem = {
  _type: 'brandLogoItem'
  logoId?:
    | 'aquafina'
    | 'asics'
    | 'asus'
    | 'bambu-lab'
    | 'bitget'
    | 'braun'
    | 'brinc'
    | 'cnn'
    | 'coca-cola'
    | 'dji'
    | 'ecoflow'
    | 'fujifilm'
    | 'govee'
    | 'hasselblad'
    | 'huawei-horizontal'
    | 'huawei-vertical'
    | 'hyundai'
    | 'insta360'
    | 'jackery'
    | 'jw-marriott'
    | 'msi'
    | 'old-spice'
    | 'oneplus'
    | 'oppo'
    | 'p-and-g'
    | 'realme'
    | 'roborock'
    | 'samsung'
    | 'taiwan-excellence'
    | 'the-north-face'
    | 'toyota-horizontal'
    | 'toyota-vertical'
    | 'unilever'
    | 'westin'
    | 'youtube'
    | 'zhiyun'
}

export type Founder = {
  _type: 'founder'
  name?: string
  jobTitle?: string
  jobTitleZh?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type AdditionalVideo = {
  _type: 'additionalVideo'
  vimeoUrl?: string
  xinpianchangUrl?: string
  videoTitle?: string
  videoTitleZh?: string
  description?: string
  descriptionZh?: string
}

export type CrewCredit = {
  _type: 'crewCredit'
  department?: 'production' | 'camera' | 'ge' | 'art' | 'casting' | 'stills' | 'post'
  isCustomRole?: boolean
  roleKey?:
    | 'brand'
    | 'agency'
    | 'production_company'
    | 'production_service'
    | 'ep'
    | 'director'
    | 'creative_director'
    | 'producer'
    | 'line_producer'
    | 'production_manager'
    | 'production_coordinator'
    | '1st_ad'
    | '2nd_ad'
    | 'pa'
    | 'product_technician'
    | 'account_manager'
    | 'transport'
    | 'chaperone'
    | 'bts'
    | 'catering'
    | 'sound_recordist'
    | 'dop'
    | 'camera_op'
    | 'steadicam_op'
    | '1st_ac'
    | '2nd_ac'
    | 'focus_puller'
    | 'camera_assistants'
    | 'dit'
    | 'qtake'
    | 'drone_op'
    | 'motion_control'
    | 'rental_house'
    | 'gaffer'
    | 'key_grip'
    | 'grip'
    | 'electrician'
    | 'production_designer'
    | 'art_director'
    | 'art_assistant'
    | 'props_master'
    | 'wardrobe'
    | 'wardrobe_assistant'
    | 'hair_makeup'
    | 'location_manager'
    | 'storyboards'
    | 'casting_director'
    | 'casting_manager'
    | 'talent'
    | 'stunt_coordinator'
    | 'choreographer'
    | 'animal_wrangler'
    | 'photographer'
    | 'photography_producer'
    | 'kv_art_director'
    | 'photography_assistant'
    | 'photo_talent'
    | 'post_supervisor'
    | 'post_house'
    | 'on_set_editor'
    | 'editor'
    | 'assistant_editors'
    | 'colorist'
    | 'sound_design_mix'
    | 'composer'
    | 'voice_over'
    | 'vfx'
    | 'online'
    | 'motion_graphics'
    | '3d_animation'
  role?: string
  people?: Array<
    {
      _key: string
    } & CrewPerson
  >
}

export type CreditIdentityReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'creditIdentity'
}

export type CrewPerson = {
  _type: 'crewPerson'
  identity?: CreditIdentityReference
  name?: string
  url?: string
  linkTitle?: string
}

export type CreditIdentity = {
  _id: string
  _type: 'creditIdentity'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  nameZh?: string
  url?: string
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | GalleryImageImage
  | TrashRecord
  | PortfolioEntryReference
  | Page
  | TrashMetadata
  | SanityFileAssetReference
  | PdfDownload
  | SanityImageCrop
  | SanityImageHotspot
  | SeoFields
  | Slug
  | CategoryReference
  | BlogPost
  | PortableTextBody
  | VideoFormatReference
  | IndustryReference
  | MarketReference
  | ClientReference
  | CrewMemberReference
  | PlatformReference
  | PortfolioEntry
  | Platform
  | TranslatedPhrase
  | CrewMember
  | Client
  | Market
  | Industry
  | VideoFormat
  | Category
  | SiteSettings
  | CampaignCta
  | VideoEmbed
  | CtaButton
  | ImageGallery
  | BrandLogoItem
  | Founder
  | AdditionalVideo
  | CrewCredit
  | CreditIdentityReference
  | CrewPerson
  | CreditIdentity
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
