<?php

if (!defined('ABSPATH')) {
    die(__FILE__);
}

return [
    [
        'name'                            => 'Image',
        'key'                             => 'fct_product_image',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => 'center',
        'textAlign'                       => 'center',
        'permalinked'                     => "yes",
        'source_type'                     => "custom",
        'wp_post_custom_data_source_type' => 'featured_image',
        'wp_post_custom_data_key'         => 'thumbnail' // use 'thumbnail' unless you have a custom size
    ],
    [
        'name'                            => 'Name',
        'key'                             => 'fct_post_title',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => 'left',
        'textAlign'                       => 'left',
        'permalinked'                     => "yes",
        'source_type'                     => "post_data",
        'wp_post_custom_data_source_type' => 'post_data',
        'wp_post_custom_data_key'         => 'post_title'
    ],
    [
        'name'                            => 'Category',
        'key'                             => 'fct_product_category',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => 'left',
        'textAlign'                       => 'left',
        'permalinked'                     => "yes",
        'filter_permalinked'              => "yes",
        'source_type'                     => "tax_data",
        'wp_post_custom_data_source_type' => "tax_data",
        'taxonomy_separator'              => ", ",
        'wp_post_custom_data_key'         => 'product-categories'
    ],
    [
        'name'                            => 'Price',
        'key'                             => 'fct_product_price',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'permalinked'                     => "no",
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => 'right',
        'textAlign'                       => 'right',
        'source_type'                     => "product_data",
        'wp_post_custom_data_source_type' => "product_data",
        'wp_post_custom_data_key'         => 'product_price' // check meta key in DB
    ],
    [
        'name'                            => 'Total Stock',
        'key'                             => 'fct_product_stock',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'permalinked'                     => "no",
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => 'center',
        'textAlign'                       => 'center',
        'source_type'                     => "product_data",
        'wp_post_custom_data_source_type' => "product_data",
        'wp_post_custom_data_key'         => 'product-stock'
    ],
    [
        'name'                            => 'Variations',
        'key'                             => 'fct_product_variations',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'permalinked'                     => "no",
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => null,
        'textAlign'                       => null,
        'source_type'                     => "product_data",
        'wp_post_custom_data_source_type' => "product_data",
        'wp_post_custom_data_key'         => 'product_variations'
    ],
    [
        'name'                            => 'Quantity',
        'key'                             => 'fct_product_quantity',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'permalinked'                     => "no",
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => null,
        'textAlign'                       => null,
        'source_type'                     => "product_data",
        'wp_post_custom_data_source_type' => "product_data",
        'wp_post_custom_data_key'         => 'product_quantity'
    ],
    [
        'name'                            => 'Buy',
        'key'                             => 'fct_product_buy',
        'breakpoints'                     => '',
        'data_type'                       => 'html',
        'width'                           => '',
        'permalinked'                     => "no",
        'header_html_content'             => null,
        'enable_html_content'             => false,
        'contentAlign'                    => null,
        'textAlign'                       => null,
        'source_type'                     => "product_data",
        'wp_post_custom_data_source_type' => "product_data",
        'wp_post_custom_data_key'         => 'buy_now_button',
        'wp_post_custom_data_value'       => 'Add To Cart',
        'show_quantity'                   => 'yes',
        'quantity_type'                   => 'normal',
        'quantity_max_value'              => ''
    ]
];
